### ISSUE TITLE
Re-export notify module

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#130]
It would be better to re-export `notify` module so that users can use the more convenient structure as follows.

Before:

```rust
// Example
use libseccomp::*;

notify::notify_id_valid();
```

After:

```rust
// Example
use libseccomp::*;

notify_id_valid();
```

Currently, I plan to re-export the `notify` module as private module as follows in order to keep the documentation clean.
However, if I do, this will be a breaking change. 

```
#[cfg(any(libseccomp_v2_5, doc))] 
mod notify;
```

If I re-export the `notify` module as public, this won't be a breaking change, but the re-exports section is added to the documentation as follows and it may be huge as new notify features are added. (I'd like to avoid writing `pub use notify::*`)
![re-export-notify-doc](https://user-images.githubusercontent.com/66765615/158057900-847989fa-7619-4906-86bc-b2d06d413e75.png)

@rusty-snake Which do you prefer? (or Could you tell me the better solution if you have?)

**Comment by rusty-snake** [comment]
The solution you described is also my preferred solution.

What we can is

```rust
#[cfg(feature = "compat_0_2")]
#[deprecated(since="0.3.0", note="...")]
pub mod notify;
#[cfg(not(feature = "compat_0_2"))]
mod notify;
```

but I think enabling a cargo feature is comparable to changing imports.

**Comment by ManaSugi** [comment]
Thank you for the suggestion. 

> I think enabling a cargo feature is comparable to changing imports.

Yes I think so. Hence, sorry to users, I'll change it without the cargo feature and add this change to CHANGELOG as an incompatible change just like v0.2.0.
