### ISSUE TITLE
MSRV

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#135]
IMHO, we should establish an <abbr title="Minimum Supported Rust Version">MSRV</abbr>.

There are two common MSRV concepts:

1. `latest stable - offset` (offset is usually 2).
    Example: The current stable rust version is 1.59, so we would CI check and guarantee that libseccomp-rs works with `rust >= (1.59 - 2 = 1.57)`.
2. A fixed release (e.g. 1.56) which is bumped from time to time (with a policy like never closes to the latest release than 2 release).

**Comment by ManaSugi** [comment]
@rusty-snake Thank you for raising this issue. This is useful for us!
I think the second approach looks good to me because we can support for users who are using the older `rustc` version.
Ref: https://github.com/tokio-rs/tokio/blob/master/.github/workflows/ci.yml#L16

Or we can the offset a little larger (than 2) in the first approach.
What do you think?

**Comment by rusty-snake** [comment]
The reason why I opened this is that we get io-safety (`OwnedFd`, `BorrowedFd<'_>` and `AsFd`) soon (maybe rust 1.62) and I like to use it for functions like `export_*`.

It's also useful if we want to go with `edition = "2021"`.

---

> Or we can the offset a little larger (than 2) in the first approach.
What do you think?

Currently we are at `1.46.0`.
pkg-config has 1.30 and will likely stick to this for a long time.

Debian stable has `1.48` and libseccomp `2.5.1`.
OpenSUSE Leap has `1.43` and Ubuntu LTS `1.57`(?)

On the one hand it would we nice to support compilation on Debian and similar w/o rustup but on the other hand it shouldn't block development.

---

More refs
- https://github.com/rusty-snake/fjp/blob/cd81884c2a3574d32c4f26b5e096e7be040eb15e/.github/workflows/rust.yml#L35
- https://github.com/actions-rs/example/blob/master/.github/workflows/msrv.yml

**Comment by ManaSugi** [comment]
> The reason why I opened this is that we get io-safety (OwnedFd, BorrowedFd<'_> and AsFd) soon (maybe rust 1.62) and I like to use it for functions like export_*.

I understand. Thank you for the information.

> On the one hand it would we nice to support compilation on Debian and similar w/o rustup but on the other hand it shouldn't block development.

Yes, this seems to be very difficult decision considering our users. In next release (v0.3.0), we can support almost features that the upstream libseccomp supports. Hence, untll v0.3.*, it would be nice to support compilation on Debian and similar at least for current libseccomp-rs users. However, from v0.4.0, I think we can set `latest stable - offset` to MSRV for users who wan to use our crate with newer rust features.

**Comment by rusty-snake** [comment]
FWIW Rust 1.63 with io_safety has been released.

**Comment by ManaSugi** [comment]
I closed this issue by #177.
@rusty-snake Thank you for great works!
