### ISSUE TITLE
More `ScmpNotifResp` constructors

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#149]
**Is your feature request related to a problem? Please describe.**

`ScmpNotifResp` has (logical) invariants you need to manage by hand.

If you specify `SECCOMP_USER_NOTIF_FLAG_CONTINUE`, `error` and `val` must be `0`.
If `error != 0`, `val` is ignored.

**Describe the solution you'd like**

Functions to construct a `ScmpNotifResp` for all responds kind (spoofed success, spoofed errorm continue):

```rust
impl ScmpNotifResp {
    fn new_val(id, val: i64) -> Self;
    fn new_error(id, error: i32) -> Self;
    fn new_continue(id) -> Self;
}
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ManaSugi** [comment]
@rusty-snake Thank you for the proposal. LGTM and this helps users invoke the notification APIs properly.
