### ISSUE TITLE
Consider a `ScmpArch::Unsupported(u32)` variant

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#150]
We should consider a `ScmpArch::Unsupported(u32)` variant which gets returned instead of ParseError by `ScmpArch::native()`.

**Comment by rusty-snake** [comment]
Yes, thinking about this gave me this idea.

**Comment by rusty-snake** [comment]
I would leave `ScmpArch` as is and handle this with an new ErrorKind instead.

```rust
ScmpArch::try_native() -> Result<ScmpArch, SeccompError(ErrorKind::UnsupportedArch(u32) | ErrorKind::Errno)>
```

**Comment by ManaSugi** [comment]
@rusty-snake Looks nice! `ErrorKind::UnsupportedArch(u32)` is better than the current `ParseError`.

**Comment by ManaSugi** [comment]
@rusty-snake Thanks for the idea!

This is my suggestions.

- `ScmpArch::from_sys` => `InvalidArch(u32)`
- `ScmpAction::from_sys` => `InvalidAction(u32)`
- `*::from_str` => `FromStrError(String)`
- `ScmpAction::from_str("SCMP_ACT_ERRNO", Some(u16::MAX+1))` => `InvalidArgument(i32)`
- `ScmpAction::from_str("SCMP_ACT_ERRNO", None)` => `MissingRequiredArgument`

or 

- `ScmpArch::from_sys`/`ScmpArch::from_str` => `InvalidArch`
- `ScmpAction::from_sys/from_str` => `InvalidAction`
- `ScmpFiltterAttr::from_str` => `InvalidAttribute`
- `ScmpAction::from_str("SCMP_ACT_TRACE", Some(u16::MAX+1))` => `InvalidArgument`
- `ScmpAction::from_str("SCMP_ACT_ERRNO", None) `=> `MissingRequiredArgument`

**Comment by ManaSugi** [comment]
@rusty-snake sorry for the late reply. more specific `ScmpAction::from_str` sounds good.

**Comment by rusty-snake** [comment]
We could also `panic!`.
