### ISSUE TITLE
Add a `ScmpNotifCookie` type

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#152]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

`struct ScmpNotifCookie(u64)` or `type ScmpNotifCookie = u64`.
The latter wouldn't be a breaking change while the former would allow `fn ScmpNotifCookie::is_valid(fd: ScmpFd) -> bool`.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ManaSugi** [comment]
Thank you for the proposal @rusty-snake.

As you mentioned in #148, I think `ScmpNotifCookie::is_valid()` and `ScmpNotifCookie::ensure_valid()` are good, but when the user wants to use those functions, the user needs to create a `ScmpNotifCookie` instance using `ScmpNotifCookie::new()`, etc. before calling them. This would be additional work and I'm not sure if it's resonable. What do you think?

**Comment by rusty-snake** [comment]
If we add a struct type for it, we should use it in Resp/Req structs like

```diff,rust
 struct ScmpNotifResp {
-    id: u64,
+    id: ScmpNotifCookie,
     ...
 }
```

On the other hand we can also say to not touch the notify API in such an breaking way for now and implement something like #163 in 0.4.0 or 0.5.0.

**Comment by ManaSugi** [comment]
@rusty-snake The new resp/req (and also new APIs of #163)  sound good me.
I think it might be good idea to consider and implement this with #163 carefully at the same time for 0.4.0 or 0.5.0 release.
Could you change the milestone if you are okay?

**Comment by rusty-snake** [comment]
--> #181
