### ISSUE TITLE
io_safety

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#166]
- `ScmpFd`
- `ScmpFilterContext::export_{bpc,pfc}`

**Comment by rusty-snake** [comment]
3. Has double borrow.
4. Will require users to call `as_fd` for no benefit.

I think I go with 1 for the export functions.

**Comment by rusty-snake** [comment]
IO-Safety for `ScmpFd` may make more sense together with #181 (one big API break).

**Comment by ManaSugi** [comment]
@rusty-snake 
Sorry for the late reply.

The 2 `fn export<T: AsFd>(fd: &mut T)` reminds me of https://github.com/libseccomp-rs/libseccomp-rs/pull/32#discussion_r762565063.

I don't have a strong opinion about it, but I'm curious about which one is better.
What do you think?

**Comment by rusty-snake** [comment]
Yes. I remember. My notes so far:
- `io::Write` is implemented for types like `Vec<u8>` as well and therefore it must take `&mut` because we write into program memory where Rusts memory-safety rules apply.
- There's no good documentation/agreement of what are the guaranties of `OwnedFd` and `BorrowedFd`.
  1. If you want to `close()`, you must take a `OwnedFd`
  2. `mmap()` is special and unlikely to ever have a safe wrapper (that provides all features).
  3. Opinion of dev1
  4. Opinion of dev2
  5. ...
- `io-lifetimes` uses `BorrowedFd`/`AsFd` in it's examples. It if for io-saftey what `futures` is for futures.
- Actaully accepting a Fd in a public API isn't perfect either. There will always be a minimal assumption. Nevermind assuming `read`/`write` is acceptable IMHO. Doing some non-unique `ioctl`s could be dangerous.

**Comment by ManaSugi** [comment]
@rusty-snake Thanks for the clarification. The solution 1 is good enough for the export function.

**Comment by rusty-snake** [comment]
`ScmpFd` will be done in #181.
