### ISSUE TITLE
Incorrect `socket` arg comparison example

### ISSUE THREAD

**Issue by anguslees** [libseccomp-rs/libseccomp-rs#189]
https://github.com/libseccomp-rs/libseccomp-rs/blob/63edce361e50347d0e0a94265d3cd24300c946c9/libseccomp/src/filter_context.rs#L360

The socket family is the _first_ arg, not second.  Thus the check _should_ be `$arg0 != AF_UNIX`.

**Comment by ManaSugi** [comment]
@anguslees Thank you for raising the issue! Exactly. I would be grateful if you could send a PR to fix it.
