### ISSUE TITLE
Reconsider SeccompErrno design for `ScmpFilterAttr::ApiSysRawRc` 

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#206]
**Is your feature request related to a problem? Please describe.**

With `ScompFilterAttr::ApiSysRawRc` enabled, some libseccomp apis will return a system's errno instead of `ECANCELED`.
But, current implementations cannot handle the system's errno other than `SeccompErrono`,  so users have to extract the errno by themselves using `std::io::Error::last_os_error()`. This is a little bit tiring.

**Describe the solution you'd like**

There are some solutions to tackle the problem.

1. Add SYSRAW(i32) to `SeccompError`:
Example:
```rust
pub enum SeccompErrno {
    ...
    SYSRAW(i32),
}
```

2. Add SYSRAW(i32) to `ErrorKind`:
Example:
```rust
pub(crate) enum ErrorKind {
    ...
    SYSRAW(i32),
}
```

3. Add all errno  to `SeccompErrno` (#205 approach):
Example:
```rust
pub enum SeccompErrno {
    ...
   EBUSY,
   EBADFD
}
```
Ref. https://docs.rs/nix/latest/src/nix/errno.rs.html#1125-1257

4. Use [`nix::Errno`](https://docs.rs/nix/latest/nix/errno/enum.Errno.html) instead of `SeccompErrno` (stop maintaining `SeccompErrno`).
Example:
```rust
pub(crate) enum ErrorKind {
    /// An error that represents error code on failure of the libseccomp API.
    Errno(nix:Errno),
    /// A parse error occurred while trying to convert a value.
    ParseError,
    ...
}
```

**Comment by rusty-snake** [comment]
From the four ideas I like 2. together with an `sysraw(self) -> Option<i32>`.

1. Makes it a enumeration of libseccomp API errors plus anything. Which isn't a clean design.
3. Also good but very verbose. Here I ask if the downsides overwigth the good sides.
4. I don't like nix and try to keep it out of my project. (I can expand on this)
