### ISSUE TITLE
Rename some functions

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#212]
**Is your feature request related to a problem? Please describe.**

Not all our functions are named idiomatic / conforming to RFC 430.

https://rust-lang.github.io/api-guidelines/checklist.html
https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case

**Describe the solution you'd like**

Rename some functions but keep deprecated aliases.

- `ScmpFilterContext::new_filter` -> `ScmpFilterContext::new`
- todo

**Comment by ManaSugi** [comment]
@rusty-snake Thanks for raising the issue.
Rename is good, and I also think `ScmpFilterContext::new` is better than `ScmpFilterContext::new_filter`.

**Comment by rusty-snake** [comment]
More candidates:
- `get_notify_fd` -> `notify_fd` or delay this to a bigger notify rework (#148, #152, #163)
