### ISSUE TITLE
Compare Argument More Than Once in a Rule

### ISSUE THREAD

**Issue by realzhujunhao** [libseccomp-rs/libseccomp-rs#267]
**Is your feature request related to a problem? Please describe.**
I want to disallow any write except for "stdout AND stderror" (that is, allow stdout and stderror, disallow any other write)
```
    use ScmpAction::*;
    
    let fd_not_stdout = scmp_cmp!($arg0 != io::stdout().as_raw_fd() as u64);
    let fd_not_stderr = scmp_cmp!($arg0 != io::stderr().as_raw_fd() as u64);

    let syscall_write = ScmpSyscall::from_name("write")?;

    let mut filter = ScmpFilterContext::new_filter(Allow)?;
    filter.add_rule_conditional(Errno(EPERM), syscall_write, &[fd_not_stderr, fd_not_stdout]);
    filter.load()?;

    let out_result = io::stdout().write_all(b"test stdout\n");
    let err_result = io::stderr().write_all(b"test stderr\n");
    let mut f = File::create("write_out.txt").unwrap();
    let f_result = f.write_all(b"test other file");
    io::stdout().flush();
    io::stderr().flush();
    f.flush();
    println!("out result\n{:?}", out_result);
    println!("err result\n{:?}", err_result);
    println!("file result\n{:?}", f_result);
```
Compile and run with
`strace -f -e trace=all -o syscall_output.txt ./filter`
gives the output
```
test stdout
test stderr
out result
Ok(())
err result
Ok(())
file result
Ok(())
```
and the file is written. (not what I expected)
syscall_output.txt snip below
```
...
218590 write(1, "test stdout\n", 12)    = 12
218590 write(2, "test stderr\n", 12)    = 12
218590 openat(AT_FDCWD, "write_out.txt", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
218590 write(3, "test other file", 15)  = 15
218590 write(1, "out result\n", 11)     = 11
218590 write(1, "Ok(())\n", 7)          = 7
218590 write(1, "err result\n", 11)     = 11
218590 write(1, "Ok(())\n", 7)          = 7
218590 write(1, "file result\n", 12)    = 12
218590 write(1, "Ok(())\n", 7)          = 7
218590 close(3)                         = 0
...
```
Where I expect fd=3 to be EPERM.

**Comment by rusty-snake** [comment]
Hi, this crate is just a wrapper around the [libseccomp](https://github.com/seccomp/libseccomp) library.

This restriction to one comparisons per argument per rule comes from the underlying library function:

> When adding syscall argument comparisons to the filter it is important to remember that while it is possible to have multiple comparisons in a single rule, you can only compare each argument once in a single rule.  In other words, you can not have multiple comparisons of the 3rd syscall argument in a single rule.
> <sub>[man:seccomp_rule_add_array(3)](https://man7.org/linux/man-pages/man3/seccomp_rule_add_array.3.html)</sub>

---

In order to allow `write(2)` only with the fds `1` and `2` (hardcoding here because it's simpler), you need to add two rules, block `fd == 0` and `fd >= 3`.


```rust
use ScmpAction::*;

let syscall_write = ScmpSyscall::from_name("write")?;

let mut filter = ScmpFilterContext::new_filter(Allow)?;
filter.add_rule_conditional(Errno(EPERM), syscall_write, &[scmp_cmp!($arg0 == 0)]);
filter.add_rule_conditional(Errno(EPERM), syscall_write, &[scmp_cmp!($arg0 >= 3)]);
filter.load()?;
```
