### ISSUE TITLE
Rework MaskedEqual compare

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#35]
The arguments of `ScmpArgCompare::new` are a bit confusing ATM. In the most cases the third argument is the value with which the argument is compared and the fourth argument is `None`. If you use `Some(_)` for the fourth argument, it is no effect. The fourth argument is therefore effectively ignore. But if you use masked equality, the third argument is the mask and the fourth argument is the value used for comparison. And if you specify it as `None` you implicitly specified 0. Not really a nice way for a high-level wrapper.

The first Idea would be to make the third argument always be the value and the fourth argument to be the mask (still and `Option<_>`). However this silently changes behaviour in a drastically way for people who just upgrade the version in Cargo.toml without reading the CHANGELOG. Moreover it would not solve the ugly `None`.

You could create a `new_masked` function. However making one op part of `ScmpArgCompare` isn't a code API design IMHO.

My current idea is to move the mask into `ScmpCompareOp`. So

```rust
ScmpArgCompare::new(0, ScmpCompareOp::Greater, 2, None);
ScmpArgCompare::new(0, ScmpCompareOp::MaskedEqual, 0b0010, Some(3));
```

becomes

```rust
ScmpArgCompare::new(0, ScmpCompareOp::Greater, 2);
ScmpArgCompare::new(0, ScmpCompareOp::MaskedEqual(0b0010), 3);
```

WDYT?

**Comment by ManaSugi** [comment]
@rusty-snake Thank you for raising this issue. I also think that the current `ScmpArgCompare::new` is a bit confusing from users' point of view and your idea seems to be good!  Could you proceed this work?
