### ISSUE TITLE
Add get/set functions for ScmpFilterAttr

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#88]
Add the following functions like the existing `{get,set}_no_new_privs_bit()`.

- [x] `get_act_default()`
- [x] `{get,set}_act_badarch()`
- [x] `{get,set}_ctl_nnp()`
- [x] `{get,set}_ctl_tsync()`
- [x] `{get,set}_ctl_log()`
- [x] `{get,set}_ctl_ssb()`
- [x] `{get,set}_ctl_optimize()`
- [x] `{get,set}_api_sysrawrc()`

**Comment by ManaSugi** [comment]
We need to decide the function name carefully to avoid under score(`_`) hell.

**Comment by ManaSugi** [comment]
I'd like to change the name of `{get,set}_no_new_privs_bit()` to `{get,set}_nnp`.
In case of `{get,set}_ssb`, If we unify the functions to full name like `{get,set}_no_new_privs`, we have to define `{get,set}_speculative_store_bypass` that is a very long name (so is `get,set}_no_new_privs_bit()`).
Hence, I propose the new function names as follows:

```rust
get_default_action()
{get,set}_badarch_action()
{get,set}_nnp()
{get,set}_log()
{get,set}_ssb()
{get,set}_optimize()
{get,set}_rawrc()
{get,set}_tskip()
{get,set}_tsync()
```
@rusty-snake Could you give me your thoughts?

Ref. https://man7.org/linux/man-pages/man3/seccomp_attr_set.3.html

**Comment by ManaSugi** [comment]
It's nice for me. Thank you.

**Comment by ManaSugi** [comment]
Regarding rename of `{get,set}_no_new_privs_bit`, Which would be better, we make the current function `deprecated` or bump the version to `0.3.0` without `deprecated`?

**Comment by rusty-snake** [comment]
IMHO we should keep it as deprecated alias even if we bump to 0.3.0.

Generally I think it is the best to just keep deprecated stuff unless it is a security risk or blocks future development.
Good examples would be
https://mesonbuild.com/Reference-manual_builtin_meson.html
https://docs.rs/clap/latest/clap/struct.Arg.html
https://doc.rust-lang.org/std/index.html

**Comment by ManaSugi** [comment]
Thank you for your suggestion and the information.
I thought that I'd like to avoid generating many deprecated functions , but I agree with your thoughts. 
I'll create  a PR to rename it with making it deprecated.
Wow, `clap` has many deprecated functions :)

**Comment by ManaSugi** [comment]
I'll decide whether we should support `{get,set}_api_tskip()` after https://github.com/seccomp/libseccomp/issues/368#issue-1118457026 is solved.
